"use client";

import React, { useRef, useState, useEffect } from "react";
import { motion, useInView } from "framer-motion";
import Link from "next/link";

// Demo clips data
interface DemoClip {
  id: string;
  title: string;
  videoUrl: string;
  description?: string;
}

const demoClips: DemoClip[] = [
  {
    id: "demo-1",
    title: "Entrepreneurship Insights",
    videoUrl: `https://res.cloudinary.com/dume4rw5s/video/upload/v1765569800/clip-1_k8bpvi.mp4`,
    description: "Key moments from startup founder interview",
  },
  {
    id: "demo-2",
    title: "Marketing Strategy",
    videoUrl: `https://res.cloudinary.com/dume4rw5s/video/upload/v1765569743/clip-2_yuhouz.mp4`,
    description: "Viral marketing tactics revealed",
  },
  {
    id: "demo-3",
    title: "Productivity Tips",
    videoUrl: `https://res.cloudinary.com/dume4rw5s/video/upload/v1765569815/clip-3_ahrv52.mp4`,
    description: "Time management secrets from experts",
  },
];

// Demo Clip Card Component
function DemoClipCard({ clip, index }: { clip: DemoClip; index: number }) {
  const cardRef = useRef(null);
  const isInView = useInView(cardRef, { once: true, margin: "-50px" });
  const [isMounted, setIsMounted] = useState(false);

  // Only render video on client side
  useEffect(() => {
    setIsMounted(true);
  }, []);

  return (
    <motion.div
      ref={cardRef}
      initial={{ opacity: 0, y: 20 }}
      animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
      transition={{
        duration: 0.5,
        delay: index * 0.1,
        ease: "easeOut",
      }}
      className="flex flex-col gap-2.5 rounded-xl border border-[#F1F1F1] bg-white p-2.5 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_10px_30px_rgba(24,62,194,0.15)]"
    >
      {/* Video Container */}
      <div className="relative aspect-[9/16] w-full overflow-hidden rounded-lg bg-[#EAEEFE]">
        {isMounted ? (
          <video
            src={clip.videoUrl}
            controls
            preload="metadata"
            className="h-full w-full object-cover"
          />
        ) : (
          // Placeholder while loading
          <div className="flex h-full w-full items-center justify-center">
            <svg
              className="h-12 w-12 animate-pulse text-[#183EC2]"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"
              />
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
          </div>
        )}
      </div>
    </motion.div>
  );
}

// Demo Clips Grid Component
function DemoClipsGrid() {
  return (
    <div className="mx-auto flex max-w-4xl justify-center">
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3">
        {demoClips.map((clip, index) => (
          <div key={clip.id} className="mx-auto w-full max-w-[280px]">
            <DemoClipCard clip={clip} index={index} />
          </div>
        ))}
      </div>
    </div>
  );
}

// Main Examples Section
export function Examples() {
  const sectionRef = useRef(null);
  const isInView = useInView(sectionRef, { once: true, margin: "-100px" });

  return (
    <section
      id="examples"
      ref={sectionRef}
      className="relative overflow-hidden bg-[#EAEEFE] py-20 md:py-24"
    >
      <div className="relative z-10 container mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
          transition={{ duration: 0.6 }}
          className="section-heading mb-16"
        >
          <div className="flex justify-center">
            <div className="tag">Examples</div>
          </div>
          <h2 className="section-title mt-5">See It in Action</h2>
          <p className="section-description mt-5">
            These clips were 100% generated by AI, with no human editing.
            <br />
            See how our technology transforms long-form podcasts into viral
            social media content.
          </p>
        </motion.div>

        {/* Clips Grid */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
          transition={{ duration: 0.6, delay: 0.2 }}
        >
          <DemoClipsGrid />
        </motion.div>

        {/* CTA Button */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="mt-16 flex justify-center"
        >
          <Link
            href="/signup"
            className="btn btn-primary group relative shadow-lg shadow-[#183EC2]/25"
          >
            <span className="inline-flex items-center text-lg">
              Try It Yourself
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="ml-2 h-5 w-5 transition-transform duration-300 ease-in-out group-hover:translate-x-1"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M13 7l5 5m0 0l-5 5m5-5H6"
                />
              </svg>
            </span>
          </Link>
        </motion.div>
      </div>
    </section>
  );
}
